[package]
name = "rg-resolver-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rg-resolver-common = { path = "../rg-resolver-common" }
serde = { version = "1.0.203", features = ["derive"] }
